// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OfficeFileAccessor;

#nullable disable

namespace OfficeFileAccessor.Migrations
{
    [DbContext(typeof(OfficeFileAccessorContext))]
    [Migration("20250304005448_CreateTableGroup")]
    partial class CreateTableGroup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OfficeFileAccessor.AppUsers.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mail");

                    b.Property<DateTime>("LastUpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Organization")
                        .HasColumnType("text")
                        .HasColumnName("organization");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("application_user");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Email = "default@example.com",
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "AQAAAAIAAYagAAAAEBnlLz94rig3PhWRgNIfS7oMLoAaLokoQ87H3Lx8T0SwgxkXaMsOt8Q3YX+IskiXfQ==",
                            UserName = "DefaultUser"
                        });
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.MergedTableCell", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("Id"));

                    b.Property<int>("EndColumn")
                        .HasColumnType("integer")
                        .HasColumnName("end_column");

                    b.Property<int>("EndRow")
                        .HasColumnType("integer")
                        .HasColumnName("end_row");

                    b.Property<int>("StartColumn")
                        .HasColumnType("integer")
                        .HasColumnName("start_column");

                    b.Property<int>("StartRow")
                        .HasColumnType("integer")
                        .HasColumnName("start_row");

                    b.Property<long>("TableCellId")
                        .HasColumnType("bigint")
                        .HasColumnName("table_cell_id");

                    b.HasKey("Id");

                    b.HasIndex("TableCellId")
                        .IsUnique();

                    b.ToTable("merged_table_cell");
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.TableCell", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("Id"));

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("text")
                        .HasColumnName("background_color");

                    b.Property<int>("Column")
                        .HasColumnType("integer")
                        .HasColumnName("column");

                    b.Property<bool>("Editabled")
                        .HasColumnType("boolean")
                        .HasColumnName("editabled");

                    b.Property<int>("HorizontalLength")
                        .HasColumnType("integer")
                        .HasColumnName("horizontal_length");

                    b.Property<int>("Row")
                        .HasColumnType("integer")
                        .HasColumnName("row");

                    b.Property<int>("TextRotation")
                        .HasColumnType("integer")
                        .HasColumnName("text_rotation");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<int>("VerticalLength")
                        .HasColumnType("integer")
                        .HasColumnName("vertical_length");

                    b.Property<bool>("VerticalWriting")
                        .HasColumnType("boolean")
                        .HasColumnName("vertical_writing");

                    b.HasKey("Id");

                    b.ToTable("table_cell");
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.TableCellBorders", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("Id"));

                    b.Property<int>("Bottom")
                        .HasColumnType("integer")
                        .HasColumnName("bottom");

                    b.Property<int>("Left")
                        .HasColumnType("integer")
                        .HasColumnName("left");

                    b.Property<int>("Right")
                        .HasColumnType("integer")
                        .HasColumnName("right");

                    b.Property<long>("TableCellId")
                        .HasColumnType("bigint")
                        .HasColumnName("table_cell_id");

                    b.Property<int>("Top")
                        .HasColumnType("integer")
                        .HasColumnName("top");

                    b.HasKey("Id");

                    b.HasIndex("TableCellId")
                        .IsUnique();

                    b.ToTable("table_cell_borders");
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.TableCellFontFormat", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("Id"));

                    b.Property<bool>("Bold")
                        .HasColumnType("boolean")
                        .HasColumnName("bold");

                    b.Property<string>("FontColor")
                        .HasColumnType("text")
                        .HasColumnName("font_color");

                    b.Property<string>("FontName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("font_name");

                    b.Property<double?>("FontSize")
                        .HasColumnType("double precision")
                        .HasColumnName("font_size");

                    b.Property<long>("TableCellId")
                        .HasColumnType("bigint")
                        .HasColumnName("table_cell_id");

                    b.HasKey("Id");

                    b.HasIndex("TableCellId")
                        .IsUnique();

                    b.ToTable("table_cell_font_format");
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.TableGroup", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("table_group");
                });

            modelBuilder.Entity("TableGroupCell", b =>
                {
                    b.Property<long>("table_cell_id")
                        .HasColumnType("bigint");

                    b.Property<long>("table_group_id")
                        .HasColumnType("bigint");

                    b.HasKey("table_cell_id", "table_group_id");

                    b.HasIndex("table_group_id");

                    b.ToTable("table_group_cell", (string)null);
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.MergedTableCell", b =>
                {
                    b.HasOne("OfficeFileAccessor.OfficeFiles.Entities.TableCell", "TableCell")
                        .WithOne("MergedCell")
                        .HasForeignKey("OfficeFileAccessor.OfficeFiles.Entities.MergedTableCell", "TableCellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TableCell");
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.TableCellBorders", b =>
                {
                    b.HasOne("OfficeFileAccessor.OfficeFiles.Entities.TableCell", "TableCell")
                        .WithOne("Borders")
                        .HasForeignKey("OfficeFileAccessor.OfficeFiles.Entities.TableCellBorders", "TableCellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TableCell");
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.TableCellFontFormat", b =>
                {
                    b.HasOne("OfficeFileAccessor.OfficeFiles.Entities.TableCell", "TableCell")
                        .WithOne("FontFormat")
                        .HasForeignKey("OfficeFileAccessor.OfficeFiles.Entities.TableCellFontFormat", "TableCellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TableCell");
                });

            modelBuilder.Entity("TableGroupCell", b =>
                {
                    b.HasOne("OfficeFileAccessor.OfficeFiles.Entities.TableCell", null)
                        .WithMany()
                        .HasForeignKey("table_cell_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeFileAccessor.OfficeFiles.Entities.TableGroup", null)
                        .WithMany()
                        .HasForeignKey("table_group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.TableCell", b =>
                {
                    b.Navigation("Borders");

                    b.Navigation("FontFormat");

                    b.Navigation("MergedCell");
                });
#pragma warning restore 612, 618
        }
    }
}
