// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OfficeFileAccessor;

#nullable disable

namespace OfficeFileAccessor.Migrations
{
    [DbContext(typeof(OfficeFileAccessorContext))]
    [Migration("20250311045550_AddShape")]
    partial class AddShape
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LinkFileSheet", b =>
                {
                    b.Property<long>("sheet_id")
                        .HasColumnType("bigint");

                    b.Property<long>("file_id")
                        .HasColumnType("bigint");

                    b.HasKey("sheet_id", "file_id");

                    b.HasIndex("file_id");

                    b.ToTable("link_file_sheet", (string)null);
                });

            modelBuilder.Entity("LinkGroupCell", b =>
                {
                    b.Property<long>("table_cell_id")
                        .HasColumnType("bigint");

                    b.Property<long>("table_group_id")
                        .HasColumnType("bigint");

                    b.HasKey("table_cell_id", "table_group_id");

                    b.HasIndex("table_group_id");

                    b.ToTable("link_group_cell", (string)null);
                });

            modelBuilder.Entity("LinkSheetColumnWidth", b =>
                {
                    b.Property<long>("column_width_id")
                        .HasColumnType("bigint");

                    b.Property<long>("sheet_id")
                        .HasColumnType("bigint");

                    b.HasKey("column_width_id", "sheet_id");

                    b.HasIndex("sheet_id");

                    b.ToTable("link_sheet_column_width", (string)null);
                });

            modelBuilder.Entity("LinkSheetGroup", b =>
                {
                    b.Property<long>("table_group_id")
                        .HasColumnType("bigint");

                    b.Property<long>("sheet_id")
                        .HasColumnType("bigint");

                    b.HasKey("table_group_id", "sheet_id");

                    b.HasIndex("sheet_id");

                    b.ToTable("link_sheet_group", (string)null);
                });

            modelBuilder.Entity("LinkSheetRowHeight", b =>
                {
                    b.Property<long>("row_height_id")
                        .HasColumnType("bigint");

                    b.Property<long>("sheet_id")
                        .HasColumnType("bigint");

                    b.HasKey("row_height_id", "sheet_id");

                    b.HasIndex("sheet_id");

                    b.ToTable("link_sheet_row_height", (string)null);
                });

            modelBuilder.Entity("OfficeFileAccessor.AppUsers.DTO.SearchUser", b =>
                {
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Organization")
                        .HasColumnType("text");

                    b.Property<int>("UseCount")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("OfficeFileAccessor.AppUsers.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mail");

                    b.Property<DateTime>("LastUpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Organization")
                        .HasColumnType("text")
                        .HasColumnName("organization");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("application_user");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Email = "default@example.com",
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "AQAAAAIAAYagAAAAEP0hMm6kXSNJY49lciGU5V3xjAI6JFszcuPMv7VZB26OKHW/od59X8CGdAVOZSEfjQ==",
                            UserName = "DefaultUser"
                        });
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.DTO.DisplayOfficeFileCell", b =>
                {
                    b.Property<string>("BackgroundColor")
                        .HasColumnType("text");

                    b.Property<bool?>("Bold")
                        .HasColumnType("boolean");

                    b.Property<int?>("BorderBottom")
                        .HasColumnType("integer");

                    b.Property<int?>("BorderLeft")
                        .HasColumnType("integer");

                    b.Property<int?>("BorderRight")
                        .HasColumnType("integer");

                    b.Property<int?>("BorderTop")
                        .HasColumnType("integer");

                    b.Property<long>("CellId")
                        .HasColumnType("bigint");

                    b.Property<int>("Column")
                        .HasColumnType("integer");

                    b.Property<bool>("Editabled")
                        .HasColumnType("boolean");

                    b.Property<string>("FontColor")
                        .HasColumnType("text");

                    b.Property<string>("FontName")
                        .HasColumnType("text");

                    b.Property<double?>("FontSize")
                        .HasColumnType("double precision");

                    b.Property<string>("Formula")
                        .HasColumnType("text");

                    b.Property<int>("GroupDisplayOrder")
                        .HasColumnType("integer");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<int>("HorizontalLength")
                        .HasColumnType("integer");

                    b.Property<int?>("MergedEndColumn")
                        .HasColumnType("integer");

                    b.Property<int?>("MergedEndRow")
                        .HasColumnType("integer");

                    b.Property<int?>("MergedStartColumn")
                        .HasColumnType("integer");

                    b.Property<int?>("MergedStartRow")
                        .HasColumnType("integer");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<long>("SheetId")
                        .HasColumnType("bigint");

                    b.Property<int>("TextRotation")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VerticalLength")
                        .HasColumnType("integer");

                    b.Property<bool>("VerticalWriting")
                        .HasColumnType("boolean");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.DTO.PreviewOfficeFileSheets", b =>
                {
                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<long>("FileId")
                        .HasColumnType("bigint");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegisterUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SheetId")
                        .HasColumnType("bigint");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.MergedTableCell", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("Id"));

                    b.Property<int>("EndColumn")
                        .HasColumnType("integer")
                        .HasColumnName("end_column");

                    b.Property<int>("EndRow")
                        .HasColumnType("integer")
                        .HasColumnName("end_row");

                    b.Property<int>("StartColumn")
                        .HasColumnType("integer")
                        .HasColumnName("start_column");

                    b.Property<int>("StartRow")
                        .HasColumnType("integer")
                        .HasColumnName("start_row");

                    b.Property<long>("TableCellId")
                        .HasColumnType("bigint")
                        .HasColumnName("table_cell_id");

                    b.HasKey("Id");

                    b.HasIndex("TableCellId")
                        .IsUnique();

                    b.ToTable("merged_table_cell");
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.OfficeFile", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("file_name");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("mime_type");

                    b.Property<int>("RegisterUserId")
                        .HasColumnType("integer")
                        .HasColumnName("register_user_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("RegisterUserId");

                    b.ToTable("office_file");
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.OfficeFileData", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("Id"));

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("file_data");

                    b.Property<long>("FileId")
                        .HasColumnType("bigint")
                        .HasColumnName("file_id");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.ToTable("office_file_data");
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.OfficeFileSheet", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("office_file_sheet");
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.Shape", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("Id"));

                    b.Property<int?>("EndColumn")
                        .HasColumnType("integer")
                        .HasColumnName("end_column");

                    b.Property<double?>("EndOffsetX")
                        .HasColumnType("double precision")
                        .HasColumnName("end_offset_x");

                    b.Property<double?>("EndOffsetY")
                        .HasColumnType("double precision")
                        .HasColumnName("end_offset_y");

                    b.Property<int?>("EndRow")
                        .HasColumnType("integer")
                        .HasColumnName("end_row");

                    b.Property<long>("OfficeFileSheetId")
                        .HasColumnType("bigint")
                        .HasColumnName("office_file_sheet_id");

                    b.Property<string>("ShapeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("shape_type");

                    b.Property<int>("StartColumn")
                        .HasColumnType("integer")
                        .HasColumnName("start_column");

                    b.Property<double>("StartOffsetX")
                        .HasColumnType("double precision")
                        .HasColumnName("start_offset_x");

                    b.Property<double>("StartOffsetY")
                        .HasColumnType("double precision")
                        .HasColumnName("start_offset_y");

                    b.Property<int>("StartRow")
                        .HasColumnType("integer")
                        .HasColumnName("start_row");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("OfficeFileSheetId");

                    b.ToTable("shape");
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.TableCell", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("Id"));

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("text")
                        .HasColumnName("background_color");

                    b.Property<int>("Column")
                        .HasColumnType("integer")
                        .HasColumnName("column");

                    b.Property<bool>("Editabled")
                        .HasColumnType("boolean")
                        .HasColumnName("editabled");

                    b.Property<string>("Formula")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("formula");

                    b.Property<int>("HorizontalLength")
                        .HasColumnType("integer")
                        .HasColumnName("horizontal_length");

                    b.Property<int>("Row")
                        .HasColumnType("integer")
                        .HasColumnName("row");

                    b.Property<int>("TextRotation")
                        .HasColumnType("integer")
                        .HasColumnName("text_rotation");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("value_type");

                    b.Property<int>("VerticalLength")
                        .HasColumnType("integer")
                        .HasColumnName("vertical_length");

                    b.Property<bool>("VerticalWriting")
                        .HasColumnType("boolean")
                        .HasColumnName("vertical_writing");

                    b.HasKey("Id");

                    b.ToTable("table_cell");
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.TableCellBorders", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("Id"));

                    b.Property<int>("Bottom")
                        .HasColumnType("integer")
                        .HasColumnName("bottom");

                    b.Property<int>("Left")
                        .HasColumnType("integer")
                        .HasColumnName("left");

                    b.Property<int>("Right")
                        .HasColumnType("integer")
                        .HasColumnName("right");

                    b.Property<long>("TableCellId")
                        .HasColumnType("bigint")
                        .HasColumnName("table_cell_id");

                    b.Property<int>("Top")
                        .HasColumnType("integer")
                        .HasColumnName("top");

                    b.HasKey("Id");

                    b.HasIndex("TableCellId")
                        .IsUnique();

                    b.ToTable("table_cell_borders");
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.TableCellFontFormat", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("Id"));

                    b.Property<bool>("Bold")
                        .HasColumnType("boolean")
                        .HasColumnName("bold");

                    b.Property<string>("FontColor")
                        .HasColumnType("text")
                        .HasColumnName("font_color");

                    b.Property<string>("FontName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("font_name");

                    b.Property<double?>("FontSize")
                        .HasColumnType("double precision")
                        .HasColumnName("font_size");

                    b.Property<long>("TableCellId")
                        .HasColumnType("bigint")
                        .HasColumnName("table_cell_id");

                    b.HasKey("Id");

                    b.HasIndex("TableCellId")
                        .IsUnique();

                    b.ToTable("table_cell_font_format");
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.TableColumnWidth", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("Id"));

                    b.Property<int>("Column")
                        .HasColumnType("integer")
                        .HasColumnName("column");

                    b.Property<double>("Width")
                        .HasColumnType("double precision")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.ToTable("table_column_width");
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.TableGroup", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("Id"));

                    b.Property<bool>("BorderedGroup")
                        .HasColumnType("boolean")
                        .HasColumnName("bordered_group");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("table_group");
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.TableRowHeight", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("Id"));

                    b.Property<double>("Height")
                        .HasColumnType("double precision")
                        .HasColumnName("height");

                    b.Property<int>("Row")
                        .HasColumnType("integer")
                        .HasColumnName("row");

                    b.HasKey("Id");

                    b.ToTable("table_row_height");
                });

            modelBuilder.Entity("LinkFileSheet", b =>
                {
                    b.HasOne("OfficeFileAccessor.OfficeFiles.Entities.OfficeFile", null)
                        .WithMany()
                        .HasForeignKey("file_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeFileAccessor.OfficeFiles.Entities.OfficeFileSheet", null)
                        .WithMany()
                        .HasForeignKey("sheet_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinkGroupCell", b =>
                {
                    b.HasOne("OfficeFileAccessor.OfficeFiles.Entities.TableCell", null)
                        .WithMany()
                        .HasForeignKey("table_cell_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeFileAccessor.OfficeFiles.Entities.TableGroup", null)
                        .WithMany()
                        .HasForeignKey("table_group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinkSheetColumnWidth", b =>
                {
                    b.HasOne("OfficeFileAccessor.OfficeFiles.Entities.TableColumnWidth", null)
                        .WithMany()
                        .HasForeignKey("column_width_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeFileAccessor.OfficeFiles.Entities.OfficeFileSheet", null)
                        .WithMany()
                        .HasForeignKey("sheet_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinkSheetGroup", b =>
                {
                    b.HasOne("OfficeFileAccessor.OfficeFiles.Entities.OfficeFileSheet", null)
                        .WithMany()
                        .HasForeignKey("sheet_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeFileAccessor.OfficeFiles.Entities.TableGroup", null)
                        .WithMany()
                        .HasForeignKey("table_group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinkSheetRowHeight", b =>
                {
                    b.HasOne("OfficeFileAccessor.OfficeFiles.Entities.TableRowHeight", null)
                        .WithMany()
                        .HasForeignKey("row_height_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeFileAccessor.OfficeFiles.Entities.OfficeFileSheet", null)
                        .WithMany()
                        .HasForeignKey("sheet_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.MergedTableCell", b =>
                {
                    b.HasOne("OfficeFileAccessor.OfficeFiles.Entities.TableCell", "TableCell")
                        .WithOne("MergedCell")
                        .HasForeignKey("OfficeFileAccessor.OfficeFiles.Entities.MergedTableCell", "TableCellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TableCell");
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.OfficeFile", b =>
                {
                    b.HasOne("OfficeFileAccessor.AppUsers.Entities.ApplicationUser", "RegisterUser")
                        .WithMany("OfficeFiles")
                        .HasForeignKey("RegisterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OfficeFile_ApplicationUser");

                    b.Navigation("RegisterUser");
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.OfficeFileData", b =>
                {
                    b.HasOne("OfficeFileAccessor.OfficeFiles.Entities.OfficeFile", "OfficeFile")
                        .WithOne("OfficeFileData")
                        .HasForeignKey("OfficeFileAccessor.OfficeFiles.Entities.OfficeFileData", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfficeFile");
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.Shape", b =>
                {
                    b.HasOne("OfficeFileAccessor.OfficeFiles.Entities.OfficeFileSheet", "Sheet")
                        .WithMany("Shapes")
                        .HasForeignKey("OfficeFileSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Shape_OfficeFileSheet");

                    b.Navigation("Sheet");
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.TableCellBorders", b =>
                {
                    b.HasOne("OfficeFileAccessor.OfficeFiles.Entities.TableCell", "TableCell")
                        .WithOne("Borders")
                        .HasForeignKey("OfficeFileAccessor.OfficeFiles.Entities.TableCellBorders", "TableCellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TableCell");
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.TableCellFontFormat", b =>
                {
                    b.HasOne("OfficeFileAccessor.OfficeFiles.Entities.TableCell", "TableCell")
                        .WithOne("FontFormat")
                        .HasForeignKey("OfficeFileAccessor.OfficeFiles.Entities.TableCellFontFormat", "TableCellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TableCell");
                });

            modelBuilder.Entity("OfficeFileAccessor.AppUsers.Entities.ApplicationUser", b =>
                {
                    b.Navigation("OfficeFiles");
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.OfficeFile", b =>
                {
                    b.Navigation("OfficeFileData");
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.OfficeFileSheet", b =>
                {
                    b.Navigation("Shapes");
                });

            modelBuilder.Entity("OfficeFileAccessor.OfficeFiles.Entities.TableCell", b =>
                {
                    b.Navigation("Borders");

                    b.Navigation("FontFormat");

                    b.Navigation("MergedCell");
                });
#pragma warning restore 612, 618
        }
    }
}
